---
title: "IAT Participant level analysis: main Step 02 Linear Mixed Modelling with Language Features"
author: "Alexander Porshnev"
date: "12/05/2025"
format:
  html:
    code-fold: true
engine: julia
julia:
  exeflags: ["--project=."]
execute:
  echo: false
  warning: false
  info: false
---

```{julia}
#| echo: false
#| results: "hidden" 
	using Pkg
	using CairoMakie        
	using DataFrames
	using MixedModels
	using MixedModelsMakie # diagnostic plots
	using Arrow
	using StandardizedPredictors
	using BoxCox
	using LinearAlgebra
	using StatsAPI
	using StatsBase
	using CSV
	using PrettyTables
  using MixedModelsExtras
  using HypothesisTests
  using Formatting
  using Markdown
  using Random
  ```

```{julia}
year = 2009  
rseed = 2192042 
#2192042: 2014 42:2009

df_A = DataFrame(Arrow.Table("../Out/$rseed/AB_split/$year-A$rseed.arrow"))
df_B = DataFrame(Arrow.Table("../Out/$rseed/AB_split/$year-B$rseed.arrow"))

```

# Analysis for `{julia} year` with 80/20 random split 
## Random seed= `{julia} rseed`


##  Main analysis requrements
../Out/`{julia} rseed`/AB_split/t_`{julia} year`A-`{julia} rseed`.arrow

../Out/`{julia} rseed`/AB_split/t_`{julia} year`(year)B-`{julia} rseed`.arrow

../in_Distances/all/`ldm_name`.csv - files with distances 

## Main analysis outputs
../Out/`{julia} rseed`/Results/bl_render_`{julia} year`.html - regression tables & summary
../Out/`{julia} rseed`/Results/results_`{julia} year`.csv - summary tables for all A,B models with BIC, R2, correlation etc.

```{julia}
#| echo: false
#| results: "hidden"

default_html = "../Out/$rseed/Results/bl_render_$year.html"
default_summary = "../Out/$rseed/Results/summary_$year"

function load_ldm(ldm_name)
    return CSV.read("../in_Distances/all/" * ldm_name * ".csv", DataFrame)
end

function init_html(file_name = default_html)
	open(file_name, "w") do io
	    show(io, "text/html", html"""<!DOCTYPE html><html><head><meta charset="UTF-8" />""")
    end
end

function close_html(file_name = default_html)
	open(file_name, "a") do io
	    show(io, "text/html", html"""</html>""")
  end
end

function print_html(smth, file_name = default_html)
   println()
   print(smth)
   open(file_name, "a") do io
	    show(io, MIME("text/html"), smth)
	 end
   #pretty_table(smth; backend = :markdown, alignment=:c)
end

function OutTable(df, file_name = default_summary)
  open(file_name * ".html", "a") do io
        pretty_table(io, df; backend = :html, alignment=:c)
	end
	pretty_table(df, backend = :html, alignment=:c)
  CSV.write(file_name * ".csv", df)
end

function OutModel(m_prec, m_next, file_name = default_html,  print_lltest= 1)
    print_html(m_next, file_name)
    if print_lltest == 1 
      try
        MixedModels.likelihoodratiotest(m_prec, m_next)
      catch e
         OutTitle("Error: MixedModels.llikelihoodratiotest failed")
         return 0
      end
      print_html(MixedModels.likelihoodratiotest(m_prec, m_next), file_name)
    end
	return 1
end

function MakeFormula(baseline, dist_name)
 return eval(Meta.parse("@formula(" * baseline * " + " * dist_name * ")"))
end

init_html()
```

# Baseline formula
compare to baseline:
baseline = "trial_latency ~
1 + age + birth_sex + countryres 
+ Length + NSyll + logBNC_freq
+ change + Order + after_error 
+ trial_number 
 + (1 | session_id) + (1|trial_name)"
 

```{julia}
#=
for testing purposes
distances=["cos_subtitles_skipgram_50_r3",
"cos_subtitles_skipgram_100_r5",
"cos_subtitles_skipgram_50_r5",
"cos_subtitles_skipgram_50_r10",
"cos_subtitles_skipgram_100_r10",
"subtitles_conditional_probability_ngram_None_r10",
"subtitles_conditional_probability_ngram_None_r3",
"subtitles_log_ngram_None_r10",
"subtitles_conditional_probability_ngram_None_r5",
"subtitles_log_ngram_None_r5",
"cos_llama_2_7b_Q8_0_pairs_names_Upper",
"cos_llama_7b_Q8_0_pairs_names_Upper",
"cos_llama_65b_Q5_0_pairs_names_Upper",
"cos_dolphin_2_8_mistral_7b_v02_Q8_0_pairs_names_Upper",
"cos_Mistral_7B_v0_3_Q8_0_pairs_names_Upper",
"cos_subtitles_probability_ratios_None_r10",
"cos_subtitles_probability_ratios_None_r5",
"cos_bnc_log_cooccurrence_None_r3",
"cos_ukwac_conditional_probability_None_r1",
"cos_bnc_log_cooccurrence_None_r5"]=#

baseline = "trial_latency ~ 1 + age + birth_sex + countryres 
+ Length + NSyll + logBNC_freq
+ change + Order + after_error 
+ trial_number 
 + (1 | session_id) + (1|trial_name)"
```
```{julia}
#| echo: false
files = readdir("../in_Distances/all/")
files = map(f -> splitext(f)[1], files)
distances = filter(f -> f != ".DS_Store", files)
```

# Baseline model statistics
```{julia}
#| echo: false

m_blA = let levels = ["m", "f", "n"], 
      form = eval(Meta.parse("@formula(" * baseline * ")"))
  contrasts = Dict(
    :birth_sex => HypothesisCoding(
      [
         1/2  0  -1/2
         0  1/2 -1/2
      ];
      levels,
      labels=["m", "f", "n"] ,),
      :countrycit => SeqDiffCoding(),
      :age => Center(24), #centered to median
      :Length => Center(6),
      :NSyll => Center(2)
   )
    fit(MixedModel, form, df_A; contrasts)
end


r2_blA_marginal = r2(m_blA; conditional = false)
r2_blA_conditional = r2(m_blA; conditional =  true)
print("## A: R2 marginal:", round(r2_blA_marginal,digits=3), " R2 conditional: ", round(r2_blA_conditional,digits=3), " BIC: ", format(bic(m_blA),width=10, precision = 0 ))

m_blB = let levels = ["m", "f", "n"]
      form = eval(Meta.parse("@formula(" * baseline * ")"))
  contrasts = Dict(
    :birth_sex => HypothesisCoding(
      [
         1/2  0  -1/2
         0  1/2 -1/2
      ];
      levels,
      labels=["m", "f", "n"],),
      :countrycit => SeqDiffCoding(),
      :age => Center(24), #centered to median
      :Length => Center(6),
      :NSyll => Center(2)
   )
    fit(MixedModel, form, df_B; contrasts)
end

r2_blB_marginal = r2(m_blB; conditional = false)
r2_blB_conditional = r2(m_blB; conditional =  true)
print("## B: R2 marginal:", round(r2_blB_marginal,digits=3), " R2 conditional: ", round(r2_blB_conditional,digits=3), " BIC: ", format(bic(m_blB),width=10, precision = 0 ))

```

```{julia}
#| echo: false
#for testing
#ldm_nameIn = distances[48]
#sample = "B"
```

```{julia}
#| echo: false
#| output: asis
function MakeModel(ldm_nameIn, sample = "A")
 OutTitle("Sample: $sample")
 dist_ldm =load_ldm(ldm_nameIn) 
 df_A.stimuli_join
 dist_ldm = transform(dist_ldm, :"first" => ByRow(passmissing(lowercase)) => :"first")
 dist_ldm[!, "stimuli_join"] = (string.(dist_ldm[!, "first"], "_", dist_ldm[!, "second"]))
 if sample=="A" 
   df1 = innerjoin(df_A, dist_ldm, on = :stimuli_join) #, renamecols = "_left" => "_right"
 else
   df1 = innerjoin(df_B, dist_ldm, on = :stimuli_join) #, renamecols = "_left" => "_right"
 end
mm_ok = true
 m_ldm = let levels = ["m", "f", "n"]
  form = MakeFormula(baseline , "ldm")
  contrasts = Dict(
    :birth_sex => HypothesisCoding(
      [
         1/2  0  -1/2
         0  1/2 -1/2
      ];
      levels,
      labels=["m", "f"],),
      :countrycit => SeqDiffCoding(),
      :age => Center(24), #centered to median
      :Length => Center(6),
      :NSyll => Center(2)
   )
 try
  fit(MixedModel, form, df1; contrasts)
 catch e
 mm_ok = false
 print_html("Error: ModelFitFailed at sample $sample")
 end
end
if mm_ok
 print(m_ldm)
 if sample=="A" 
  OutModel(m_blA, m_ldm, default_html, 1)
  b_bic = bic(m_blA)
  r2_bl_marginal = r2(m_blA; conditional = false)
  r2_bl_conditional = r2(m_blA; conditional =  true)
 else
  OutModel(m_blB, m_ldm, default_html,1)
  b_bic = bic(m_blB)
  r2_bl_marginal = r2(m_blB; conditional = false)
  r2_bl_conditional = r2(m_blB; conditional =  true)
 end
 
 r2_ldm_marginal = r2(m_ldm; conditional = false)
 r2_ldm_conditional = r2(m_ldm; conditional =  true)

 f2 = (r2_ldm_conditional - r2_bl_conditional)/(1 - r2_ldm_conditional)

 #dfCor = select(iat,[:"trial_latency",:"ldm"])
 cor_RT_ldm = cor(df1[!, "trial_latency"], df1[!,"ldm"])
 ct = CorrelationTest(df1[!, "trial_latency"], df1[!,"ldm"])

 ci = confint(ct)
 lower_bound = ci[1]
 upper_bound = ci[2]
 #print(cor_RT_ldm, lower_bound, upper_bound )
 #round(lower_bound,sigdigits = 3)

 ldmx_coef= "NA"
 m_CI = confint(m_ldm; level=0.95)
 m_Coefs = coef(m_ldm)
 m_Coefs_names = coefnames(m_ldm)
 for i in 1:size(m_Coefs_names)[1]
   if cmp(m_Coefs_names[i],"ldm")==0
    ldmx_coef=m_Coefs[i]
   end
 end

 ldmX_CI = m_CI["ldm"] 

 squared_r = map(x -> x^2, residuals(m_ldm))
 rmsea =sqrt(mean(squared_r))

 modelStats = DataFrame([(sample = sample,
            model = ldm_nameIn, 
						BIC = format(bic(m_ldm),width=10, precision = 0),
						dBIC = (b_bic -bic(m_ldm)),
						R2_ldm_marginal = r2_ldm_marginal,
						R2_ldm_conditional = r2_ldm_conditional,
						f2_conditional = f2,
						Cor = cor_RT_ldm,
            CI = (lower_bound, upper_bound),
            coef_lmd = ldmx_coef,
            coef_CI = (string(ldmX_CI[2]) *","*  string(ldmX_CI[3])),
            RMSEA = rmsea)
						])
 return modelStats 
 else
  modelStats = DataFrame([(sample = sample,
            model = ldm_nameIn, 
						BIC = 0,
						dBIC = 0,
						R2_ldm_marginal = 0,
						R2_ldm_conditional = 0,
						f2_conditional = 0,
						Cor = 0,
            CI = (0, 0),
            coef_lmd = 0,
            coef_CI = ("0","0"),
            RMSEA = 0)
						])
 return modelStats
 end
end
```


# Linear mixed models with language features (distances)

```{julia}

function OutTitle(text) 
#| echo: false
#| output: asis
    text = replace(text, "_" => ".")
    print_html(Markdown.parse("## $text"))
end
```


```{julia} 
#| echo: false
modelStatsRes = DataFrame()
for i in 1:length(distances) 
# [48;274] #$[1:47; 49:273; 275:length(distances)]
# 48, 274 under question
  name = distances[i]
  OutTitle("$i.LDM: $name")

  modelStatsRes = append!(modelStatsRes, MakeModel(distances[i], "A"))
  modelStatsRes = append!(modelStatsRes, MakeModel(distances[i], "B"))
end 
```

## Summary also saved in HTML: bl_render.html and CSV: results.csv
```{julia}
OutTable(modelStatsRes)
```

```{julia}
close_html()
``` 